# Generated by Django 5.0.3 on 2024-03-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('python', models.IntegerField(default=0)),
                ('java', models.IntegerField(default=0)),
                ('javaScript', models.IntegerField(default=0)),
            ],
        ),
    ]
